create table if not exists public.conversion_rates (
    id bigint generated by default as identity primary key,
    src_currency text not null,
    dst_currency text not null,
    rate numeric not null,
    created_at timestamp with time zone default now(),
    unique(src_currency, dst_currency)
);

alter table public.conversion_rates enable row level security;

create policy "Enable read access for authenticated users"
on public.conversion_rates for select
to authenticated
using (true);

-- Seed data
insert into public.conversion_rates (src_currency, dst_currency, rate)
values 
('USD', 'VND', 24000),
('VND', 'USD', 1.0/24000)
on conflict (src_currency, dst_currency) do update
set rate = excluded.rate;

create or replace function get_conversion_rate(src_currency text, dst_currency text)
returns numeric
language plpgsql
as $$
declare
    conversion_rate numeric;
begin
    if src_currency = dst_currency then
        return 1.0;
    end if;

    select rate into conversion_rate
    from public.conversion_rates
    where conversion_rates.src_currency = get_conversion_rate.src_currency
      and conversion_rates.dst_currency = get_conversion_rate.dst_currency;
      
    if conversion_rate is null then
        return 0;
    end if;
    
    return conversion_rate;
end;
$$;
