create table if not exists public.configurations (
    id bigint generated by default as identity,
    config_key text not null,
    config_value text not null,
    config_category text not null default 'default',
    description text,
    "tenant_code" text references tenants(code) default null,
    created_at timestamp with time zone default now()
);

CREATE UNIQUE INDEX configurations_pkey ON public.configurations USING btree (id);
alter table "public"."configurations" add constraint "configurations_pkey" PRIMARY KEY using index "configurations_pkey";
