create table "public"."cycles" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "start_time" timestamptz not null,
    "end_time" timestamptz not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid references auth.users(id) default auth.uid(),
    "updated_by" uuid references auth.users(id) default auth.uid(),
    "tenant_code" text references tenants(code) default null
);

alter table "public"."cycles" enable row level security;

CREATE UNIQUE INDEX cycles_pkey ON public.cycles USING btree (id);

alter table "public"."cycles" add constraint "cycles_pkey" PRIMARY KEY using index "cycles_pkey";

create policy "Users can manage their own cycles" on "public"."cycles"
as permissive for all
to authenticated
using (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2')
with check (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2');