create table "public"."finance_checkin_records" (
    "id" bigint generated by default as identity not null,
    "balance" bigint,
    "currency" text,
    "ledger_id" bigint references ledgers(id) not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid references auth.users(id) default auth.uid(),
    "updated_by" uuid references auth.users(id) default auth.uid(),
    "tenant_code" text references tenants(code) default null
);

alter table "public"."finance_checkin_records" enable row level security;

CREATE UNIQUE INDEX finance_checkin_records_pkey ON public.finance_checkin_records USING btree (id);

alter table "public"."finance_checkin_records" add constraint "finance_checkin_records_pkey" PRIMARY KEY using index "finance_checkin_records_pkey";

create policy "Users can manage their own finance checkin records" on "public"."finance_checkin_records"
as permissive for all
to authenticated
using (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2')
with check (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2');