create table "public"."notes" (
    "id" bigint generated by default as identity not null,
    "title" text,
    "content" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid references auth.users(id) default auth.uid(),
    "updated_by" uuid references auth.users(id) default auth.uid(),
    "tenant_code" text references tenants(code) default null
);

alter table "public"."notes" enable row level security;

CREATE UNIQUE INDEX notes_pkey ON public.notes USING btree (id);

alter table "public"."notes" add constraint "notes_pkey" PRIMARY KEY using index "notes_pkey";