create table "public"."wish_list_items" (
    "id" bigint generated by default as identity not null,
    "title" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid references auth.users(id) default auth.uid(),
    "updated_by" uuid references auth.users(id) default auth.uid(),
    "tenant_code" text references tenants(code) default null
);

alter table "public"."wish_list_items" enable row level security;

CREATE UNIQUE INDEX wish_list_items_pkey ON public.wish_list_items USING btree (id);

alter table "public"."wish_list_items" add constraint "wish_list_items_pkey" PRIMARY KEY using index "wish_list_items_pkey";

create table "public"."wish_list_items_track" (
    "id" bigint generated by default as identity not null,
    "wish_list_item_id" bigint references wish_list_items(id) not null,
    "point" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid references auth.users(id) default auth.uid(),
    "updated_by" uuid references auth.users(id) default auth.uid(),
    "tenant_code" text references tenants(code) default null
);

alter table "public"."wish_list_items_track" enable row level security;

CREATE UNIQUE INDEX wish_list_items_track_pkey ON public.wish_list_items_track USING btree (id);

alter table "public"."wish_list_items_track" add constraint "wish_list_items_track_pkey" PRIMARY KEY using index "wish_list_items_track_pkey";

create policy "Users can manage their own wish list items" on "public"."wish_list_items"
as permissive for all
to authenticated
using (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2')
with check (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2');

create policy "Users can manage their own wish list items track" on "public"."wish_list_items_track"
as permissive for all
to authenticated
using (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2')
with check (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2');