create table "public"."ledgers" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid references auth.users(id) default auth.uid(),
    "updated_by" uuid references auth.users(id) default auth.uid(),
    "tenant_code" text references tenants(code) default null
);

alter table "public"."ledgers" enable row level security;

CREATE UNIQUE INDEX ledgers_pkey ON public.ledgers USING btree (id);

alter table "public"."ledgers" add constraint "ledgers_pkey" PRIMARY KEY using index "ledgers_pkey";

CREATE TYPE transaction_type AS ENUM  ('credit', 'debit');

create table "public"."transactions" (
    "id" bigint generated by default as identity not null,
    "ledger_id" bigint references ledgers(id) not null,
    "amount" bigint,
    "currency" text,
    "type" transaction_type,
    "description" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "created_by" uuid references auth.users(id) default auth.uid(),
    "updated_by" uuid references auth.users(id) default auth.uid(),
    "tenant_code" text references tenants(code) default null
);

alter table "public"."transactions" enable row level security;

CREATE UNIQUE INDEX transactions_pkey ON public.transactions USING btree (id);

alter table "public"."transactions" add constraint "transactions_pkey" PRIMARY KEY using index "transactions_pkey";

create policy "Users can manage their own ledgers" on "public"."ledgers"
as permissive for all
to authenticated
using (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2')
with check (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2');

create policy "Users can manage their own transactions" on "public"."transactions"
as permissive for all
to authenticated
using (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2')
with check (auth.uid() = created_by and (auth.jwt() ->> 'aal') = 'aal2');